name: Publish to TestPyPI
on:
  push:
    branches:
      - main
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine build
          pip install -r requirements.txt
      - name: Install Node dependencies
        run: |
          yarn
          npm run build
      - name: Test with pytest
        run: |
          pip install -r tests/requirements.txt
          pytest tests
      - name: Build and publish to TestPyPI
        run: |
          # Install the package from setup.py
          python3 -m build
          python3 -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ dist/* --verbose
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
