name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install -r tests/requirements.txt
          pytest tests
      - name: Install build
        run: |
          pip install build
      - name: Build and publish to TestPyPI
        run: |
          # Install the package from setup.py
          python3 -m build
          python3 -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ dist/* --verbose
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
