name: Publish Python 🐍 distributions 📦 TestPyPI

on:
  push:
    branches:
      - main
# on: push

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 TestPyPI
    runs-on: ubuntu-18.04
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
       with:
        node-version: 12
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
        python-version: '3.x'
     - name: Install Python dependencies
       run: |
         python3 -m pip install --upgrade pip
         python3 -m pip install setuptools wheel twine
         pip install -r requirements.txt
     - name: Install Node dependencies
       run: |
         npm install | echo "npm install error occurred"
         npm run build
     - name: Test with pytest
       run: |
         pip install -r tests/requirements.txt
         pytest tests
     - name: Build
       run: |
         # Install the package from setup.py
         python3 setup.py install
         python3 setup.py sdist bdist_wheel
         # python3 -m twine upload dist/*
         twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*
       env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}

   
